[mgr]
prepend_keymap = [
  { on = "<Esc>",   run = "quit",               desc = "Quit Yazi" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" }
]
prepend_fetchers = [
  { id = "git", name = "*", run  = "git" }
]
